import { MODULES } from './principal';

export const GEN_AUTHORITIES = {
  CODE: MODULES.GENERAL.CODE,
  SEGURIDAD: {
    CODE: MODULES.GENERAL.SUBS.SEGURIDAD,
    REGISTRAR_ACTUALIZAR_USUARIOS: `${MODULES.GENERAL.SUBS.SEGURIDAD}002`,
    GESTIONAR_PERMISOS_USUARIO_ROL: `${MODULES.GENERAL.SUBS.SEGURIDAD}003`,
    CREAR_PERMISOS: `${MODULES.GENERAL.SUBS.SEGURIDAD}004`,
  },
};
